In [1]:
#importing dependencies
import pandas as pd
from datetime import datetime as dt

In [2]:
df= pd.read_csv('Datasources/US_youtube_trending_data.csv')
df

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ‚ñ∂ http://bit.ly/Subscrib...
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL ‚Üí http://bit.ly/subscribe-xxl...
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69186,XeuXShFIgyc,Why Millions Buy Harley-Davidson Motorcycles,2021-07-11T15:00:13Z,UCNSMdQtn1SuFzCZjfK2C7dQ,FortNine,2,2021-07-17T00:00:00Z,[None],658387,41703,577,4927,https://i.ytimg.com/vi/XeuXShFIgyc/default.jpg,False,False,People say these motorbikes are overpriced tra...
69187,CLUNE8OVvEw,CHANNEL UPDATE: The UNCERTAIN Future of the Be...,2021-07-11T12:27:01Z,UCcAd5Np7fO8SeejB1FVKcYw,Best Ever Food Review Show,19,2021-07-17T00:00:00Z,best ever food review show|befrs team|sonny si...,1634819,90834,1741,8116,https://i.ytimg.com/vi/CLUNE8OVvEw/default.jpg,False,False,üè• DONATE TO VIETNAM‚ÄôS COVID-19 VACCINE FUND ¬ª...
69188,NLffKOOyxwI,hospital,2021-07-10T14:02:33Z,UCOsATJw-IZgqGT8MFrHjKGg,Ice Cream Sandwich,23,2021-07-17T00:00:00Z,[None],1898048,188757,788,10159,https://i.ytimg.com/vi/NLffKOOyxwI/default.jpg,False,False,"The first 1,000 people to use this link will g..."
69189,r16Rz2J5IZo,If Water Fights Were Like Video Games,2021-07-09T15:00:11Z,UCn3AViOfcFN4zIICMC5hvPg,Shiloh & Bros,22,2021-07-17T00:00:00Z,nerf|blaster|nerf blaster|nerf battle|gaming|v...,9736240,107627,6452,8919,https://i.ytimg.com/vi/r16Rz2J5IZo/default.jpg,False,False,"A summer 2021 day with super soakers, water bl..."
69190,KISlIJDOMJU,HIDE & SEEK ON KSI‚Äôs PRIVATE JET,2021-07-10T18:00:06Z,UCh5mLn90vUaB1PbRRx_AiaA,MoreSidemen,22,2021-07-17T00:00:00Z,sidemen|moresidemen|miniminter|ksi|zerkaa|behz...,4929197,356030,3250,5540,https://i.ytimg.com/vi/KISlIJDOMJU/default.jpg,False,False,‚Ä¢ Sidemen: http://www.youtube.com/Sidemen‚Ä¢ Sid...

In [3]:
#leaving the columns we want to work with 
youtube_df= df[['video_id','title','publishedAt','channelId','channelTitle','categoryId','trending_date', 'tags','view_count','likes','dislikes' ]]

youtube_df

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964
...,...,...,...,...,...,...,...,...,...,...,...
69186,XeuXShFIgyc,Why Millions Buy Harley-Davidson Motorcycles,2021-07-11T15:00:13Z,UCNSMdQtn1SuFzCZjfK2C7dQ,FortNine,2,2021-07-17T00:00:00Z,[None],658387,41703,577
69187,CLUNE8OVvEw,CHANNEL UPDATE: The UNCERTAIN Future of the Be...,2021-07-11T12:27:01Z,UCcAd5Np7fO8SeejB1FVKcYw,Best Ever Food Review Show,19,2021-07-17T00:00:00Z,best ever food review show|befrs team|sonny si...,1634819,90834,1741
69188,NLffKOOyxwI,hospital,2021-07-10T14:02:33Z,UCOsATJw-IZgqGT8MFrHjKGg,Ice Cream Sandwich,23,2021-07-17T00:00:00Z,[None],1898048,188757,788
69189,r16Rz2J5IZo,If Water Fights Were Like Video Games,2021-07-09T15:00:11Z,UCn3AViOfcFN4zIICMC5hvPg,Shiloh & Bros,22,2021-07-17T00:00:00Z,nerf|blaster|nerf blaster|nerf battle|gaming|v...,9736240,107627,6452
69190,KISlIJDOMJU,HIDE & SEEK ON KSI‚Äôs PRIVATE JET,2021-07-10T18:00:06Z,UCh5mLn90vUaB1PbRRx_AiaA,MoreSidemen,22,2021-07-17T00:00:00Z,sidemen|moresidemen|miniminter|ksi|zerkaa|behz...,4929197,356030,3250

In [4]:
youtube_df['publishedAt'].astype

<bound method NDFrame.astype of 0        2020-08-11T19:20:14Z
1        2020-08-11T17:00:10Z
2        2020-08-11T16:34:06Z
3        2020-08-11T16:38:55Z
4        2020-08-11T15:10:05Z
                 ...
69186    2021-07-11T15:00:13Z
69187    2021-07-11T12:27:01Z
69188    2021-07-10T14:02:33Z
69189    2021-07-09T15:00:11Z
69190    2021-07-10T18:00:06Z
Name: publishedAt, Length: 69191, dtype: object>

In [5]:
#transforming the datetime to new format
youtube_df['publishedAt'] = youtube_df['publishedAt'].str.split('T').str[0]
youtube_df['trending_date'] = youtube_df['trending_date'].str.split('T').str[0]
youtube_df.head()

<ipython-input-5-6089bcb2f34f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youtube_df['publishedAt'] = youtube_df['publishedAt'].str.split('T').str[0]
<ipython-input-5-6089bcb2f34f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youtube_df['trending_date'] = youtube_df['trending_date'].str.split('T').str[0]

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964

In [6]:
dict = {'video_id': 'Video_id',
        'title': 'Title',
        'publishedAt': 'Published_date',
        'channelId': 'Chanel_id',
        'channelTitle': 'Channel_Title',
        'categoryId':'Category_id',
        'trending_date':"Trending_date" ,
        'tags':'Tags', 
        'view_count':'View_count', 
        'likes':'Likes',
        'dislikes':'Dislikes'            
                
        
       }
  
# call rename () method
youtube_df.rename(columns=dict,
          inplace=True)
  
# print Data frame after rename columns
youtube_df

C:\Users\squiros\Anaconda3\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Video_id,Title,Published_date,Chanel_id,Channel_Title,Category_id,Trending_date,Tags,View_count,Likes,Dislikes
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964
...,...,...,...,...,...,...,...,...,...,...,...
69186,XeuXShFIgyc,Why Millions Buy Harley-Davidson Motorcycles,2021-07-11,UCNSMdQtn1SuFzCZjfK2C7dQ,FortNine,2,2021-07-17,[None],658387,41703,577
69187,CLUNE8OVvEw,CHANNEL UPDATE: The UNCERTAIN Future of the Be...,2021-07-11,UCcAd5Np7fO8SeejB1FVKcYw,Best Ever Food Review Show,19,2021-07-17,best ever food review show|befrs team|sonny si...,1634819,90834,1741
69188,NLffKOOyxwI,hospital,2021-07-10,UCOsATJw-IZgqGT8MFrHjKGg,Ice Cream Sandwich,23,2021-07-17,[None],1898048,188757,788
69189,r16Rz2J5IZo,If Water Fights Were Like Video Games,2021-07-09,UCn3AViOfcFN4zIICMC5hvPg,Shiloh & Bros,22,2021-07-17,nerf|blaster|nerf blaster|nerf battle|gaming|v...,9736240,107627,6452
69190,KISlIJDOMJU,HIDE & SEEK ON KSI‚Äôs PRIVATE JET,2021-07-10,UCh5mLn90vUaB1PbRRx_AiaA,MoreSidemen,22,2021-07-17,sidemen|moresidemen|miniminter|ksi|zerkaa|behz...,4929197,356030,3250

In [7]:
youtube_df.drop('Tags', axis=1, inplace=True)
youtube_df

C:\Users\squiros\Anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Video_id,Title,Published_date,Chanel_id,Channel_Title,Category_id,Trending_date,View_count,Likes,Dislikes
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12,1514614,156908,5855
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12,2381688,146739,2794
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12,2038853,353787,2628
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12,496771,23251,1856
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12,1123889,45802,964
...,...,...,...,...,...,...,...,...,...,...
69186,XeuXShFIgyc,Why Millions Buy Harley-Davidson Motorcycles,2021-07-11,UCNSMdQtn1SuFzCZjfK2C7dQ,FortNine,2,2021-07-17,658387,41703,577
69187,CLUNE8OVvEw,CHANNEL UPDATE: The UNCERTAIN Future of the Be...,2021-07-11,UCcAd5Np7fO8SeejB1FVKcYw,Best Ever Food Review Show,19,2021-07-17,1634819,90834,1741
69188,NLffKOOyxwI,hospital,2021-07-10,UCOsATJw-IZgqGT8MFrHjKGg,Ice Cream Sandwich,23,2021-07-17,1898048,188757,788
69189,r16Rz2J5IZo,If Water Fights Were Like Video Games,2021-07-09,UCn3AViOfcFN4zIICMC5hvPg,Shiloh & Bros,22,2021-07-17,9736240,107627,6452
69190,KISlIJDOMJU,HIDE & SEEK ON KSI‚Äôs PRIVATE JET,2021-07-10,UCh5mLn90vUaB1PbRRx_AiaA,MoreSidemen,22,2021-07-17,4929197,356030,3250

In [8]:
import json

In [9]:
with open('Datasources/US_category_id.json') as f:
    data= json.load(f)

In [10]:
data

{'kind': 'youtube#videoCategoryListResponse',
 'etag': 'HIrK3n45Uw2IYz9_U2-gK1OsXvo',
 'items': [{'kind': 'youtube#videoCategory',
   'etag': 'IfWa37JGcqZs-jZeAyFGkbeh6bc',
   'id': '1',
   'snippet': {'title': 'Film & Animation',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '5XGylIs7zkjHh5940dsT5862m1Y',
   'id': '2',
   'snippet': {'title': 'Autos & Vehicles',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'HCjFMARbBeWjpm6PDfReCOMOZGA',
   'id': '10',
   'snippet': {'title': 'Music',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'ra8H7xyAfmE2FewsDabE3TUSq10',
   'id': '15',
   'snippet': {'title': 'Pets & Animals',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '7mqChSJogdF3hSIL-88BfDE-W8M',
   'id': '17',
   'snippet': {'title': 'Sports',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '0Z6uGkj97NgjD-X3pkA-nL18Hqk',
   'id': '18',
   'snippet': {'title': 'Short Movies',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'K_-7stg0kIU7eUBOPUa6j5fqIMQ',
   'id': '19',
   'snippet': {'title': 'Travel & Events',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'I3IL9xGIM3MsULlqR4tvCsEKv98',
   'id': '20',
   'snippet': {'title': 'Gaming',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'D1W6tq5mMMCV0wtNxf9A6g9wWjU',
   'id': '21',
   'snippet': {'title': 'Videoblogging',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'QMEBz6mxVdklVaq8JwesPEw_4nI',
   'id': '22',
   'snippet': {'title': 'People & Blogs',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'v2n6q4JttoL4uUbazrcxNQRGPZk',
   'id': '23',
   'snippet': {'title': 'Comedy',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'Qi1csjh-POReitZEbR7CUw7dmao',
   'id': '24',
   'snippet': {'title': 'Entertainment',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'IbGXblQi8v_nOsXjirhul1NVcH8',
   'id': '25',
   'snippet': {'title': 'News & Politics',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'gYzt8dB8mlod-84ipMtjynYe9xU',
   'id': '26',
   'snippet': {'title': 'Howto & Style',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'hHUhloYhyMMqVkQ4LH9sr3aRQoU',
   'id': '27',
   'snippet': {'title': 'Education',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'KEdEtUd4WGk_aACrYI03UhGE33w',
   'id': '28',
   'snippet': {'title': 'Science & Technology',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'AioSVwhKNpZ2bhtw9SJmrkfY5-I',
   'id': '29',
   'snippet': {'title': 'Nonprofits & Activism',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'tMfbFvkfuPP8YnUEqpr0gcR6aWU',
   'id': '30',
   'snippet': {'title': 'Movies',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'totPMF_82XTvVFy0ExFgoKhTklM',
   'id': '31',
   'snippet': {'title': 'Anime/Animation',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'LNgRKNynxC50MeYV9e6XLPX9JC4',
   'id': '32',
   'snippet': {'title': 'Action/Adventure',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'harT7v7A6516SPdkqp81Xy5yfBw',
   'id': '33',
   'snippet': {'title': 'Classics',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'M6Y5Av0CP45r5GgpzamLfHj41y4',
   'id': '34',
   'snippet': {'title': 'Comedy',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'ZFbZGeeLYWolvmCLQM7m8Yio104',
   'id': '35',
   'snippet': {'title': 'Documentary',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'FD7naICnxxl8HOnZZJAzrWplzuU',
   'id': '36',
   'snippet': {'title': 'Drama',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '7fvdoCRRWE89SpB5UaOY8gGdbk0',
   'id': '37',
   'snippet': {'title': 'Family',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'H6d6HrYDy3EAVAxQR8Z-ShEva1k',
   'id': '38',
   'snippet': {'title': 'Foreign',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'Z3yra5IR8n2bkjvv3ZheAOQ-tUk',
   'id': '39',
   'snippet': {'title': 'Horror',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '3F8eda4xnGzGFmlpsFaf5_YpOgU',
   'id': '40',
   'snippet': {'title': 'Sci-Fi/Fantasy',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'HwuNLGhBJ4PZCEurr-SoqvHuKx8',
   'id': '41',
   'snippet': {'title': 'Thriller',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': 'qJ2eDOZWUDj8fbFYAIG_yzPCYRc',
   'id': '42',
   'snippet': {'title': 'Shorts',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '2sKmjip5q7FHJgqkHvnpMDgmddE',
   'id': '43',
   'snippet': {'title': 'Shows',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}},
  {'kind': 'youtube#videoCategory',
   'etag': '3IaZjRK8JeIkLMfRDX57P4FFb9A',
   'id': '44',
   'snippet': {'title': 'Trailers',
    'assignable': False,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}]}

In [11]:
df= pd.DataFrame(data['items'])
df_merge = pd.concat([df,pd.json_normalize(df.snippet)], axis=1)
df_merge

,kind,etag,id,snippet,title,assignable,channelId
0,youtube#videoCategory,IfWa37JGcqZs-jZeAyFGkbeh6bc,1,"{'title': 'Film & Animation', 'assignable': Tr...",Film & Animation,True,UCBR8-60-B28hp2BmDPdntcQ
1,youtube#videoCategory,5XGylIs7zkjHh5940dsT5862m1Y,2,"{'title': 'Autos & Vehicles', 'assignable': Tr...",Autos & Vehicles,True,UCBR8-60-B28hp2BmDPdntcQ
2,youtube#videoCategory,HCjFMARbBeWjpm6PDfReCOMOZGA,10,"{'title': 'Music', 'assignable': True, 'channe...",Music,True,UCBR8-60-B28hp2BmDPdntcQ
3,youtube#videoCategory,ra8H7xyAfmE2FewsDabE3TUSq10,15,"{'title': 'Pets & Animals', 'assignable': True...",Pets & Animals,True,UCBR8-60-B28hp2BmDPdntcQ
4,youtube#videoCategory,7mqChSJogdF3hSIL-88BfDE-W8M,17,"{'title': 'Sports', 'assignable': True, 'chann...",Sports,True,UCBR8-60-B28hp2BmDPdntcQ
5,youtube#videoCategory,0Z6uGkj97NgjD-X3pkA-nL18Hqk,18,"{'title': 'Short Movies', 'assignable': False,...",Short Movies,False,UCBR8-60-B28hp2BmDPdntcQ
6,youtube#videoCategory,K_-7stg0kIU7eUBOPUa6j5fqIMQ,19,"{'title': 'Travel & Events', 'assignable': Tru...",Travel & Events,True,UCBR8-60-B28hp2BmDPdntcQ
7,youtube#videoCategory,I3IL9xGIM3MsULlqR4tvCsEKv98,20,"{'title': 'Gaming', 'assignable': True, 'chann...",Gaming,True,UCBR8-60-B28hp2BmDPdntcQ
8,youtube#videoCategory,D1W6tq5mMMCV0wtNxf9A6g9wWjU,21,"{'title': 'Videoblogging', 'assignable': False...",Videoblogging,False,UCBR8-60-B28hp2BmDPdntcQ
9,youtube#videoCategory,QMEBz6mxVdklVaq8JwesPEw_4nI,22,"{'title': 'People & Blogs', 'assignable': True...",People & Blogs,True,UCBR8-60-B28hp2BmDPdntcQ
10,youtube#videoCategory,v2n6q4JttoL4uUbazrcxNQRGPZk,23,"{'title': 'Comedy', 'assignable': True, 'chann...",Comedy,True,UCBR8-60-B28hp2BmDPdntcQ
11,youtube#videoCategory,Qi1csjh-POReitZEbR7CUw7dmao,24,"{'title': 'Entertainment', 'assignable': True,...",Entertainment,True,UCBR8-60-B28hp2BmDPdntcQ
12,youtube#videoCategory,IbGXblQi8v_nOsXjirhul1NVcH8,25,"{'title': 'News & Politics', 'assignable': Tru...",News & Politics,True,UCBR8-60-B28hp2BmDPdntcQ
13,youtube#videoCategory,gYzt8dB8mlod-84ipMtjynYe9xU,26,"{'title': 'Howto & Style', 'assignable': True,...",Howto & Style,True,UCBR8-60-B28hp2BmDPdntcQ
14,youtube#videoCategory,hHUhloYhyMMqVkQ4LH9sr3aRQoU,27,"{'title': 'Education', 'assignable': True, 'ch...",Education,True,UCBR8-60-B28hp2BmDPdntcQ
15,youtube#videoCategory,KEdEtUd4WGk_aACrYI03UhGE33w,28,"{'title': 'Science & Technology', 'assignable'...",Science & Technology,True,UCBR8-60-B28hp2BmDPdntcQ
16,youtube#videoCategory,AioSVwhKNpZ2bhtw9SJmrkfY5-I,29,"{'title': 'Nonprofits & Activism', 'assignable...",Nonprofits & Activism,True,UCBR8-60-B28hp2BmDPdntcQ
17,youtube#videoCategory,tMfbFvkfuPP8YnUEqpr0gcR6aWU,30,"{'title': 'Movies', 'assignable': False, 'chan...",Movies,False,UCBR8-60-B28hp2BmDPdntcQ
18,youtube#videoCategory,totPMF_82XTvVFy0ExFgoKhTklM,31,"{'title': 'Anime/Animation', 'assignable': Fal...",Anime/Animation,False,UCBR8-60-B28hp2BmDPdntcQ
19,youtube#videoCategory,LNgRKNynxC50MeYV9e6XLPX9JC4,32,"{'title': 'Action/Adventure', 'assignable': Fa...",Action/Adventure,False,UCBR8-60-B28hp2BmDPdntcQ
20,youtube#videoCategory,harT7v7A6516SPdkqp81Xy5yfBw,33,"{'title': 'Classics', 'assignable': False, 'ch...",Classics,False,UCBR8-60-B28hp2BmDPdntcQ
21,youtube#videoCategory,M6Y5Av0CP45r5GgpzamLfHj41y4,34,"{'title': 'Comedy', 'assignable': False, 'chan...",Comedy,False,UCBR8-60-B28hp2BmDPdntcQ
22,youtube#videoCategory,ZFbZGeeLYWolvmCLQM7m8Yio104,35,"{'title': 'Documentary', 'assignable': False, ...",Documentary,False,UCBR8-60-B28hp2BmDPdntcQ
23,youtube#videoCategory,FD7naICnxxl8HOnZZJAzrWplzuU,36,"{'title': 'Drama', 'assignable': False, 'chann...",Drama,False,UCBR8-60-B28hp2BmDPdntcQ
24,youtube#videoCategory,7fvdoCRRWE89SpB5UaOY8gGdbk0,37,"{'title': 'Family', 'assignable': False, 'chan...",Family,False,UCBR8-60-B28hp2BmDPdntcQ
25,youtube#videoCategory,H6d6HrYDy3EAVAxQR8Z-ShEva1k,38,"{'title': 'Foreign', 'assignable': False, 'cha...",Foreign,False,UCBR8-60-B28hp2BmDPdntcQ
26,youtube#videoCategory,Z3yra5IR8n2bkjvv3ZheAOQ-tUk,39,"{'title': 'Horror', 'assignable': False, 'chan...",Horror,False,UCBR8-60-B28hp2BmDPdntcQ
27,youtube#videoCategory,3F8eda4xnGzGFmlpsFaf5_YpOgU,40,"{'title': 'Sci-Fi/Fantasy', 'assignable': Fals...",Sci-Fi/Fantasy,False,UCBR8-60-B28hp2BmDPdntcQ
28,youtube#videoCategory,HwuNLGhBJ4PZCEurr-SoqvHuKx8,41,"{'title': 'Thriller', 'assignable': False, 'ch...",Thriller,False,UCBR8-60-B28hp2BmDPdntcQ
29,youtube#videoCategory,qJ2eDOZWUDj8fbFYAIG_yzPCYRc,42,"{'title': 'Shorts', 'assignable': False, 'chan...",Shorts,False,UCBR8-60-B28hp2BmDPdntcQ
30,youtube#videoCategory,2sKmjip5q7FHJgqkHvnpMDgmddE,43,"{'title': 'Shows', 'assignable': False, 'chann...",Shows,False,UCBR8-60-B28hp2BmDPdntcQ
31,youtube#videoCategory,3IaZjRK8JeIkLMfRDX57P4FFb9A,44,"{'title': 'Trailers', 'assignable': False, 'ch...",Trailers,False,UCBR8-60-B28hp2BmDPdntcQ

In [12]:
df_test = pd.json_normalize(data['items'])
df_test

,kind,etag,id,snippet.title,snippet.assignable,snippet.channelId
0,youtube#videoCategory,IfWa37JGcqZs-jZeAyFGkbeh6bc,1,Film & Animation,True,UCBR8-60-B28hp2BmDPdntcQ
1,youtube#videoCategory,5XGylIs7zkjHh5940dsT5862m1Y,2,Autos & Vehicles,True,UCBR8-60-B28hp2BmDPdntcQ
2,youtube#videoCategory,HCjFMARbBeWjpm6PDfReCOMOZGA,10,Music,True,UCBR8-60-B28hp2BmDPdntcQ
3,youtube#videoCategory,ra8H7xyAfmE2FewsDabE3TUSq10,15,Pets & Animals,True,UCBR8-60-B28hp2BmDPdntcQ
4,youtube#videoCategory,7mqChSJogdF3hSIL-88BfDE-W8M,17,Sports,True,UCBR8-60-B28hp2BmDPdntcQ
5,youtube#videoCategory,0Z6uGkj97NgjD-X3pkA-nL18Hqk,18,Short Movies,False,UCBR8-60-B28hp2BmDPdntcQ
6,youtube#videoCategory,K_-7stg0kIU7eUBOPUa6j5fqIMQ,19,Travel & Events,True,UCBR8-60-B28hp2BmDPdntcQ
7,youtube#videoCategory,I3IL9xGIM3MsULlqR4tvCsEKv98,20,Gaming,True,UCBR8-60-B28hp2BmDPdntcQ
8,youtube#videoCategory,D1W6tq5mMMCV0wtNxf9A6g9wWjU,21,Videoblogging,False,UCBR8-60-B28hp2BmDPdntcQ
9,youtube#videoCategory,QMEBz6mxVdklVaq8JwesPEw_4nI,22,People & Blogs,True,UCBR8-60-B28hp2BmDPdntcQ
10,youtube#videoCategory,v2n6q4JttoL4uUbazrcxNQRGPZk,23,Comedy,True,UCBR8-60-B28hp2BmDPdntcQ
11,youtube#videoCategory,Qi1csjh-POReitZEbR7CUw7dmao,24,Entertainment,True,UCBR8-60-B28hp2BmDPdntcQ
12,youtube#videoCategory,IbGXblQi8v_nOsXjirhul1NVcH8,25,News & Politics,True,UCBR8-60-B28hp2BmDPdntcQ
13,youtube#videoCategory,gYzt8dB8mlod-84ipMtjynYe9xU,26,Howto & Style,True,UCBR8-60-B28hp2BmDPdntcQ
14,youtube#videoCategory,hHUhloYhyMMqVkQ4LH9sr3aRQoU,27,Education,True,UCBR8-60-B28hp2BmDPdntcQ
15,youtube#videoCategory,KEdEtUd4WGk_aACrYI03UhGE33w,28,Science & Technology,True,UCBR8-60-B28hp2BmDPdntcQ
16,youtube#videoCategory,AioSVwhKNpZ2bhtw9SJmrkfY5-I,29,Nonprofits & Activism,True,UCBR8-60-B28hp2BmDPdntcQ
17,youtube#videoCategory,tMfbFvkfuPP8YnUEqpr0gcR6aWU,30,Movies,False,UCBR8-60-B28hp2BmDPdntcQ
18,youtube#videoCategory,totPMF_82XTvVFy0ExFgoKhTklM,31,Anime/Animation,False,UCBR8-60-B28hp2BmDPdntcQ
19,youtube#videoCategory,LNgRKNynxC50MeYV9e6XLPX9JC4,32,Action/Adventure,False,UCBR8-60-B28hp2BmDPdntcQ
20,youtube#videoCategory,harT7v7A6516SPdkqp81Xy5yfBw,33,Classics,False,UCBR8-60-B28hp2BmDPdntcQ
21,youtube#videoCategory,M6Y5Av0CP45r5GgpzamLfHj41y4,34,Comedy,False,UCBR8-60-B28hp2BmDPdntcQ
22,youtube#videoCategory,ZFbZGeeLYWolvmCLQM7m8Yio104,35,Documentary,False,UCBR8-60-B28hp2BmDPdntcQ
23,youtube#videoCategory,FD7naICnxxl8HOnZZJAzrWplzuU,36,Drama,False,UCBR8-60-B28hp2BmDPdntcQ
24,youtube#videoCategory,7fvdoCRRWE89SpB5UaOY8gGdbk0,37,Family,False,UCBR8-60-B28hp2BmDPdntcQ
25,youtube#videoCategory,H6d6HrYDy3EAVAxQR8Z-ShEva1k,38,Foreign,False,UCBR8-60-B28hp2BmDPdntcQ
26,youtube#videoCategory,Z3yra5IR8n2bkjvv3ZheAOQ-tUk,39,Horror,False,UCBR8-60-B28hp2BmDPdntcQ
27,youtube#videoCategory,3F8eda4xnGzGFmlpsFaf5_YpOgU,40,Sci-Fi/Fantasy,False,UCBR8-60-B28hp2BmDPdntcQ
28,youtube#videoCategory,HwuNLGhBJ4PZCEurr-SoqvHuKx8,41,Thriller,False,UCBR8-60-B28hp2BmDPdntcQ
29,youtube#videoCategory,qJ2eDOZWUDj8fbFYAIG_yzPCYRc,42,Shorts,False,UCBR8-60-B28hp2BmDPdntcQ
30,youtube#videoCategory,2sKmjip5q7FHJgqkHvnpMDgmddE,43,Shows,False,UCBR8-60-B28hp2BmDPdntcQ
31,youtube#videoCategory,3IaZjRK8JeIkLMfRDX57P4FFb9A,44,Trailers,False,UCBR8-60-B28hp2BmDPdntcQ

In [13]:
categories_df = df_test[['id','snippet.title']].rename(columns={'id':'categoryid','snippet.title': 'categorytitle'})
categories_df

   categoryid          categorytitle
0           1       Film & Animation
1           2       Autos & Vehicles
2          10                  Music
3          15         Pets & Animals
4          17                 Sports
5          18           Short Movies
6          19        Travel & Events
7          20                 Gaming
8          21          Videoblogging
9          22         People & Blogs
10         23                 Comedy
11         24          Entertainment
12         25        News & Politics
13         26          Howto & Style
14         27              Education
15         28   Science & Technology
16         29  Nonprofits & Activism
17         30                 Movies
18         31        Anime/Animation
19         32       Action/Adventure
20         33               Classics
21         34                 Comedy
22         35            Documentary
23         36                  Drama
24         37                 Family
25         38                Foreign
26         39                 Horror
27         40         Sci-Fi/Fantasy
28         41               Thriller
29         42                 Shorts
30         43                  Shows
31         44               Trailers

In [30]:
channel_df = youtube_df[['Channel_Title']].drop_duplicates(ignore_index=True)
channel_df

           Channel_Title
0               Brawadis
1           Apex Legends
2          jacksepticeye
3                    XXL
4               Mr. Kate
...                  ...
3619                Buur
3620         shakiraVEVO
3621           FUNK FLEX
3622              Chewkz
3623  Quadeca Exclusives

[3624 rows x 1 columns]

In [31]:
#creating the channel table
youtube_df['Chanel_id'] = youtube_df.apply(lambda x:channel_df[(channel_df.Channel_Title == x.Channel_Title)].index[0], axis=1)
youtube_df.head()

<ipython-input-31-6073d8d65233>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youtube_df['Chanel_id'] = youtube_df.apply(lambda x:channel_df[(channel_df.Channel_Title == x.Channel_Title)].index[0], axis=1)

,Video_id,Title,Published_date,Chanel_id,Channel_Title,Category_id,Trending_date,View_count,Likes,Dislikes,title_id
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11,0,Brawadis,22,2020-08-12,1514614,156908,5855,0
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11,1,Apex Legends,20,2020-08-12,2381688,146739,2794,1
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11,2,jacksepticeye,24,2020-08-12,2038853,353787,2628,2
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11,3,XXL,10,2020-08-12,496771,23251,1856,3
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11,4,Mr. Kate,26,2020-08-12,1123889,45802,964,4

In [63]:
[f"{x}: {youtube_df[x].nunique()}" for x in youtube_df.columns]
#youtube_df.loc[~youtube_df[["Video_id","Channel_Title","Published_date", "Category_id"]].duplicated()]
#any(youtube_df[["Trending_date","Video_id"]].duplicated())

['Video_id: 11603',
 'Title: 11851',
 'Published_date: 347',
 'Chanel_id: 3624',
 'Channel_Title: 3624',
 'Category_id: 15',
 'Trending_date: 326',
 'View_count: 68282',
 'Likes: 57296',
 'Dislikes: 11672',
 'title_id: 11851']

In [22]:
title_df = youtube_df[['Title']].drop_duplicates(ignore_index=True).rename(columns = {'index' : 'titleid','Title':'title'})

                                                   title
0                     I ASKED HER TO BE MY GIRLFRIEND...
1      Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...
2      I left youtube for a month and THIS is what ha...
3      XXL 2020 Freshman Class Revealed - Official An...
4      Ultimate DIY Home Movie Theater for The LaBran...
...                                                  ...
11846                       This is Starting to Get Ugly
11847      Ice Cream - You Suck at Cooking (episode 130)
11848                            Trope Talk: All A Dream
11849  Shattering a Wine Glass with Sound at 187,500F...
11850                Would YOU Quit School For $100,000?

[11851 rows x 1 columns]

In [24]:
# youtube_df['title_id'] = youtube_df.apply(lambda x:title_df[(title_df.title == x.Title)].index[0], axis=1)
# youtube_df.head()

<ipython-input-24-3f143cb681f3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youtube_df['title_id'] = youtube_df.apply(lambda x:title_df[(title_df.title == x.Title)].index[0], axis=1)

,Video_id,Title,Published_date,Chanel_id,Channel_Title,Category_id,Trending_date,View_count,Likes,Dislikes,title_id
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12,1514614,156908,5855,0
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...,2020-08-11,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12,2381688,146739,2794,1
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12,2038853,353787,2628,2
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12,496771,23251,1856,3
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12,1123889,45802,964,4

In [26]:
youtube_df.Title.nunique()

11851

In [56]:
from sqlalchemy import create_engine

In [57]:
engine = create_engine('postgresql://postgres:postgres@localhost:5432/youtube_db')
connection = engine.connect()

In [58]:
engine.table_names()

['channel', 'videos', 'category', 'titles']

In [59]:
categories_df.to_sql(name='category', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "category_pkey"
DETAIL:  Key (categoryid)=(1) already exists.

[SQL: INSERT INTO category (categoryid, categorytitle) VALUES (%(categoryid)s, %(categorytitle)s)]
[parameters: ({'categoryid': '1', 'categorytitle': 'Film & Animation'}, {'categoryid': '2', 'categorytitle': 'Autos & Vehicles'}, {'categoryid': '10', 'categorytitle': 'Music'}, {'categoryid': '15', 'categorytitle': 'Pets & Animals'}, {'categoryid': '17', 'categorytitle': 'Sports'}, {'categoryid': '18', 'categorytitle': 'Short Movies'}, {'categoryid': '19', 'categorytitle': 'Travel & Events'}, {'categoryid': '20', 'categorytitle': 'Gaming'}  ... displaying 10 of 32 total bound parameter sets ...  {'categoryid': '43', 'categorytitle': 'Shows'}, {'categoryid': '44', 'categorytitle': 'Trailers'})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [60]:
channel_df.to_sql(name='channel', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "channel_pkey"
DETAIL:  Key (channelid)=(UCi5iiEyLwSLvlqnMi02u5gQ) already exists.

[SQL: INSERT INTO channel (channelid, channeltitle) VALUES (%(channelid)s, %(channeltitle)s)]
[parameters: ({'channelid': 'UCvtRTOMP2TqYqu51xNrqAzg', 'channeltitle': 'Brawadis'}, {'channelid': 'UC0ZV6M2THA81QT9hrVWJG3A', 'channeltitle': 'Apex Legends'}, {'channelid': 'UCYzPXprvl5Y-Sf0g4vX-m6g', 'channeltitle': 'jacksepticeye'}, {'channelid': 'UCbg_UMjlHJg_19SZckaKajg', 'channeltitle': 'XXL'}, {'channelid': 'UCDVPcEbVLQgLZX0Rt6jo34A', 'channeltitle': 'Mr. Kate'}, {'channelid': 'UC5zJwsFtEs9WYe3A76p7xIA', 'channeltitle': 'Professor Live'}, {'channelid': 'UCDSJCBYqL7VQrlXfhr1RtwA', 'channeltitle': 'Les Do Makeup'}, {'channelid': 'UC2C_jShtL725hvbm1arSV9w', 'channeltitle': 'CGP Grey'}  ... displaying 10 of 3628 total bound parameter sets ...  {'channelid': 'UC2z8HLrUbudYX_fTyLzpptw', 'channeltitle': 'Chewkz'}, {'channelid': 'UCj0wNjiFUUaHw_Uc_QHybMg', 'channeltitle': 'Quadeca Exclusives'})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [66]:
title_df.to_sql(name='titles', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "titles_pkey"
DETAIL:  Key (titleid)=(0) already exists.

[SQL: INSERT INTO titles (titleid, title) VALUES (%(titleid)s, %(title)s)]
[parameters: ({'titleid': 0, 'title': 'I ASKED HER TO BE MY GIRLFRIEND...'}, {'titleid': 1, 'title': 'Apex Legends | Stories from the Outlands ‚Äì ‚ÄúThe Endorsement‚Äù'}, {'titleid': 2, 'title': 'I left youtube for a month and THIS is what happened.'}, {'titleid': 3, 'title': 'XXL 2020 Freshman Class Revealed - Official Announcement'}, {'titleid': 4, 'title': 'Ultimate DIY Home Movie Theater for The LaBrant Family!'}, {'titleid': 5, 'title': "I Haven't Been Honest About My Injury.. Here's THE TRUTH"}, {'titleid': 6, 'title': 'OUR FIRST FAMILY INTRO!!'}, {'titleid': 7, 'title': 'CGP Grey was WRONG'}  ... displaying 10 of 11851 total bound parameter sets ...  {'titleid': 69032, 'title': 'Shattering a Wine Glass with Sound at 187,500FPS - The Slow Mo Guys'}, {'titleid': 69132, 'title': 'Would YOU Quit School For $100,000?'})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [62]:
pd.read_sql_query('select * from category' , con = engine).head()

   categoryid     categorytitle
0           1  Film & Animation
1           2  Autos & Vehicles
2          10             Music
3          15    Pets & Animals
4          17            Sports

In [63]:
pd.read_sql_query('select * from titles' , con = engine).head()

   titleid                                              title
0        0                 I ASKED HER TO BE MY GIRLFRIEND...
1        1  Apex Legends | Stories from the Outlands ‚Äì ‚ÄúTh...
2        2  I left youtube for a month and THIS is what ha...
3        3  XXL 2020 Freshman Class Revealed - Official An...
4        4  Ultimate DIY Home Movie Theater for The LaBran...

In [64]:
pd.read_sql_query('select * from channel' , con = engine).head()

Empty DataFrame
Columns: [channelid, channeltitle]
Index: []